apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - autoscaler.yaml
  - aws-ebs-csi-driver.yaml
  - aws-efs-csi-driver.yaml
  - eks.yaml
  - gatekeeper.yaml
  - loki.yaml
  - bitnami.yaml
  - prometheus-community.yaml
  - fairwinds-stable.yaml
  - kyverno.yaml