apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: '8.2.0'
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: nginx-values

