apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kube-system
spec:
  releaseName: kyverno
  targetNamespace: kyverno
  interval: 1m
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 1m
  values:
   