apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: kube-system
spec:
  releaseName: vpa
  interval: 1m
  chart:
    spec:
      chart: vpa
      #      version: '1.1.1'
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system
      interval: 1m
