---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s-config/apps/podinfo/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps-nginx
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s-config/apps/nginx/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client