apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: kube-system
spec:
  releaseName: istio
  interval: 1m
  chart:
    spec:
      chart: istio
      version: ''
      sourceRef:
        kind: HelmRepository
        name: isto
        namespace: flux-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: isto-values
    