apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  releaseName: aws-load-balancer-controller
  interval: 1m
  chart:
    spec:
      chart: aws-load-balancer-controller
      #    version: 'v2.1.0'
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    clusterName: flux
    capabilities:
      drop:
        - ALL
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
